### ISSUE TITLE
Issue on group page

### ISSUE THREAD

**Issue by edimitchel** [simonaco/page-transitions-travelapp#12]
Hello,

when I clicked on a person in the group page, the first lady is showing big (it's a mistake comparing to the [vue/nuxt verison](https://page-transitions.com/group)

![image](https://user-images.githubusercontent.com/2922851/44662811-22cea700-aa0f-11e8-863e-770f4957e60f.png)

**Comment by simonaco** [comment]
Oh, you're right. thanks for the feedback, I'll make sure to fix this.

**Comment by simonaco** [comment]
Fixed by #14. Thanks again for your feedback! 🙋🏼
